const MERCHANT_INFO_QUERY = 'MERCHANT_INFO_QUERY';
const MERCHANT_INFO_SET = 'MERCHANT_INFO_SET';
const TABLE_INFO_SET = 'TABLE_INFO_SET';
const NUMBER_OF_PEOPLE_SET = 'NUMBER_OF_PEOPLE_SET';
const CART_ITEMS_CLEAR = 'CART_ITEMS_CLEAR';
const CART_ITEMS_SYNC = 'CART_ITEMS_SYNC';
const DISH_LIST_QUERY = 'DISH_LIST_QUERY';
const DISH_MINUS = 'DISH_MINUS';
const DISH_PLUS = 'DISH_PLUS';
const CATEGORY_LIST_SET = 'CATEGORY_LIST_SET';
const UNPAID_DISH_LIST_CREATE = 'UNPAID_DISH_LIST_CREATE';
const UNPAID_DISH_LIST_QUERY = 'UNPAID_DISH_LIST_QUERY';
const TOP_BAR_VISIBILITY_SET = 'TOP_BAR_VISIBILITY_SET';
const ORDER_CREATE_BY_ALI = 'ORDER_CREATE_BY_ALI';
const ORDER_CREATE_BY_WECHAT = 'ORDER_CREATE_BY_WECHAT';
const CURRENT_BROWSER_SET = 'CURRENT_BROWSER_SET';
const QR_CODE_VISIBILITY_SET = 'QR_CODE_VISIBILITY_SET';
const QR_CODE_GET = 'QR_CODE_GET';
const ORDER_STATUS_SET = 'ORDER_STATUS_SET';
const ORDER_INFO_SYNC = 'ORDER_INFO_SYNC';


export default {
    TOP_BAR_VISIBILITY_SET,
    MERCHANT_INFO_QUERY,
    TABLE_INFO_SET,
    NUMBER_OF_PEOPLE_SET,
    CART_ITEMS_CLEAR,
    CART_ITEMS_SYNC,
    MERCHANT_INFO_SET,
    DISH_LIST_QUERY,
    CATEGORY_LIST_SET,
    UNPAID_DISH_LIST_CREATE,
    UNPAID_DISH_LIST_QUERY,
    DISH_MINUS,
    DISH_PLUS,
    ORDER_CREATE_BY_ALI,
    ORDER_CREATE_BY_WECHAT,
    CURRENT_BROWSER_SET,
    QR_CODE_VISIBILITY_SET,
    QR_CODE_GET,
    ORDER_STATUS_SET,
    ORDER_INFO_SYNC
};